return {
  { -- Fuzzy Finder (files, lsp, etc)
    'nvim-telescope/telescope.nvim',
    event = 'VimEnter',
    dependencies = {
      'nvim-lua/plenary.nvim',
      { -- If encountering errors, see telescope-fzf-native README for installation instructions
        'nvim-telescope/telescope-fzf-native.nvim',
        build = 'make',
        cond = function()
          return vim.fn.executable 'make' == 1
        end,
      },
      { 'nvim-telescope/telescope-ui-select.nvim' },
      { 'nvim-tree/nvim-web-devicons', enabled = vim.g.have_nerd_font },
    },
    config = function()
      require('telescope').setup {
        defaults = {
          vimgrep_arguments = {
            'rg',
            '--color=never',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case',
            '--glob',
            '!**/.git/*',
            '--glob',
            '!**/node_modules/*',
            '--glob',
            '!**/target/*',
            '--glob',
            '!**/.next/*',
            '--glob',
            '!**/.svelte-kit/*',
            '--glob',
            '!**/dist/*',
            '--glob',
            '!**/build/*',
            '--glob',
            '!**/.venv/*',
            '--glob',
            '!**/__pycache__/*',
            '--glob',
            '!**/.dart_tool/*',
            '--glob',
            '!**/.dub/*',
            '--glob',
            '!**/vendor/*',
            '--glob',
            '!**/.cache/*',
            '--glob',
            '!**/bin/*',
            '--glob',
            '!**/obj/*',
          },
          layout_strategy = 'horizontal',
          max_results = 2000,
          path_display = { 'smart' },
        },
        pickers = {
          find_files = {
            find_command = {
              'rg',
              '--files',
              '--glob',
              '!**/.git/*',
              '--glob',
              '!**/node_modules/*',
              '--glob',
              '!**/target/*',
              '--glob',
              '!**/.next/*',
              '--glob',
              '!**/.svelte-kit/*',
              '--glob',
              '!**/dist/*',
              '--glob',
              '!**/build/*',
              '--glob',
              '!**/.venv/*',
              '--glob',
              '!**/__pycache__/*',
              '--glob',
              '!**/.dart_tool/*',
              '--glob',
              '!**/.dub/*',
              '--glob',
              '!**/vendor/*',
              '--glob',
              '!**/.cache/*',
              '--glob',
              '!**/bin/*',
              '--glob',
              '!**/obj/*',
            },
          },

        },
        extensions = {
          ['ui-select'] = {
            require('telescope.themes').get_dropdown(),
          },
        },
      }
      pcall(require('telescope').load_extension, 'fzf')
      pcall(require('telescope').load_extension, 'ui-select')
    end,
  },
}
